version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 8
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "[Type] Tech Debt"
      - "[Area] Dependencies"
    ignore:
      # Automattic libraries have a custom versioning scheme which doesn't work with Dependabot.
      - dependency-name: "com.automattic:Automattic-Tracks-Android"
      - dependency-name: "com.automattic:encryptedlogging"
      - dependency-name: "com.automattic.tracks:crashlogging"
      - dependency-name: "com.automattic.android.measure-builds"
      # Ignore Compose dependencies as they often need to be updated together
      - dependency-name: "androidx.compose:compose-bom"
      - dependency-name: "com.google.android.horologist:horologist-audio-ui"
      - dependency-name: "com.google.android.horologist:horologist-audio"
      - dependency-name: "com.google.android.horologist:horologist-auth-composables"
      - dependency-name: "com.google.android.horologist:horologist-auth-data"
      - dependency-name: "com.google.android.horologist:horologist-auth-data-phone"
      - dependency-name: "com.google.android.horologist:horologist-auth-ui"
      - dependency-name: "com.google.android.horologist:horologist-compose-layout"
      - dependency-name: "com.google.android.horologist:horologist-compose-material"
      - dependency-name: "com.google.android.horologist:horologist-datalayer"
      - dependency-name: "com.google.android.horologist:horologist-media"
      - dependency-name: "com.google.android.horologist:horologist-media-ui"
      - dependency-name: "com.google.android.horologist:horologist-media3-outputswitcher"
      - dependency-name: "com.google.android.horologist:horologist-network-awareness-okhttp"
      - dependency-name: "androidx.wear.compose:compose-foundation"
      - dependency-name: "androidx.wear.compose:compose-material"
      - dependency-name: "androidx.wear.compose:compose-navigation"
      # Ignore KSP as it needs to be updated together with Kotlin
      - dependency-name: "com.google.devtools.ksp"
