updates:
  - package-ecosystem: "github-actions"
    commit-message:
      prefix: "Actions"
    directory: "/" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"

  - package-ecosystem: "gradle"
    commit-message:
      prefix: "Gradle"
    directory: "/" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"

  - package-ecosystem: "gradle"
    commit-message:
      prefix: "Gradle"
    directory: "/app"
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"

  - package-ecosystem: "gradle"
    commit-message:
      prefix: "Gradle"
    directory: "/automotive" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"

  - package-ecosystem: "gradle"
    commit-message:
      prefix: "Gradle"
    directory: "/wear"
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"

  - package-ecosystem: "maven"
    commit-message:
      prefix: "Maven"
    directory: "/" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"
      
  - package-ecosystem: "maven"
    commit-message:
      prefix: "Maven"
    directory: "/app" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"

  - package-ecosystem: "maven"
    commit-message:
      prefix: "Maven"
    directory: "/automotive" 
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"

  - package-ecosystem: "maven"
    commit-message:
      prefix: "Maven"
    directory: "/wear"
    schedule:
      day: "saturday"
      interval: "weekly"
      time: "03:00"

version: 2
