blank_issues_enabled: true
contact_links:
  - name: ğŸš€ Feature request
    url: https://forums.pocketcasts.com/
    about: Suggest a new feature on the forum. We'll consider building it if it receives sufficient interest!
  - name: ğŸ’¬ Pocket Casts forums
    url: https://forums.pocketcasts.com/
    about: Get help with Pocket Casts at our public forum.
  - name: â“Help FAQ
    url: https://support.pocketcasts.com/android/
    about: Check the FAQ for solutions to common app issues.
